### ISSUE TITLE
Additional / late connections joining room not getting captions stream

### ISSUE THREAD

**Issue by noopkat** [a11yproject/Wordcast#10]
Currently the exact order is needed in order to successfully receive captions:

1. Create a room
2. Open a new tab and visit that room
3. Start broadcasting on the first tab via viewMode param page refresh

Any later connections wishing to view a room do not receive the captions, as it's limited to the first socket connection only I believe. I could be barking up the wrong tree.

BTW awesome project, I'd like to open a few PR's to start this train going again ☺️

**Comment by davatron5000** [comment]
Wow! Thanks Suz. I'll try to carve out some time next week to review these but this looks awesome. Thanks so much for picking it up.

**Comment by JordanForeman** [comment]
To echo Dave, thanks for picking this up @noopkat! I've signed off on your PRs - they all look good to me! @davatron5000 if you'd like me to merge them, I can. For now I'll leave them open until you're able to review them yourself.

**Comment by davatron5000** [comment]
Merge on! Thanks @noopkat.
