### ISSUE TITLE
Repeat 2 times speech

### ISSUE THREAD

**Issue by johnfelipe** [a11yproject/Wordcast#14]
![cc](https://cloud.githubusercontent.com/assets/428820/7428157/79fad8a4-efb0-11e4-9f20-dd349502e3c0.png)

How fix that

**Comment by JordanForeman** [comment]
@davatron5000 had mentioned this waaaaay back when I first made this page. https://github.com/a11yproject/Wordcast/pull/5#issuecomment-32957554

I can fix easily enough. This isn't particularly the best way to view the captions - a better view would be to only display one line at a time (the active one) and constantly update it as more words are spoken and added to the "phrase". As it is now, this log view doesn't make a lot of sense. 

If we _do_ decide to keep a log (which seems like a reasonable feature), we would probably want to leverage the [continuous attribute](https://dvcs.w3.org/hg/speech-api/raw-file/tip/speechapi.html#dfn-continuous) to avoid this kind of duplication.

**Comment by johnfelipe** [comment]
But in tablet work fine, why this behavior, look
![screenshot_2015-05-01-14-05-52](https://cloud.githubusercontent.com/assets/428820/7435672/44cc8f00-f00b-11e4-8570-df78e40b0f2c.png)

**Comment by johnfelipe** [comment]
Please help me to fix it

**Comment by johnfelipe** [comment]
any progress with my problem?

**Comment by JordanForeman** [comment]
@johnfelipe try it out now - it should be fixed :smile:

**Comment by johnfelipe** [comment]
@JordanForeman hi my pal pls help me for update with Closed Caption looks like in actual realese...
